name: Build

on:
  push:
    branches: [ master ]

jobs:
  call_pipeline:
    runs-on: ubuntu-latest

    steps:
    - run: |
        curl \
        -XPOST \
        -u "tbrand-aa:${{ secrets.PA_TOKEN }}" \
        -H "Accept: application/vnd.github.everest-preview+json" \
        -H "Content-Type: application/json" https://api.github.com/repos/tbrand-aa/pipeline-base/dispatches \
        --data '{"event_type": "project-build_${{ format(github.repository, \'/\', \'_\') }}", "client_payload": { "environment": "acceptance" }}'
