name: Build

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  call_pipeline:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'tim-brand/pipeline-base'
        ref: 'v0.1.2'
        path: 'base-actions'
    - run: |
        repo="${github_repo////_}"
        echo "::set-env name=repo::$repo"
      env:
        github_repo: ${{ github.repository }}
    - name: 'Build module trigger'
      uses: ./base-actions/.github/actions/build-module
      with:
        type: 'integration-test_${{ env.repo }}'
        environment: 'acceptance'
        repository-name: ${{ github.repository }}
        repository-sha: ${{ github.sha }}
#    - run: |
#        curl \
#        -XPOST \
#        -H "Authorization: token ${{ secrets.PA_TOKEN }}" \
#        -H "Accept: application/vnd.github.everest-preview+json" \
#        -H "Content-Type: application/json" https://api.github.com/repos/tbrand-aa/pipeline-base/dispatches \
#        --data '{"event_type": "integration-test_${{ env.repo }}", "client_payload": { "environment": "acceptance", "repository_name": "${{ github.repository }}", "repository_sha": "${{ github.sha }}"  }}'
