name: Rotate Auth

on:
  # schedule:
  #   - cron:  '*/30 * * * *'

jobs:
  call_pipeline:
    runs-on: ubuntu-latest

    steps:
    - run: |
        repo="${github_repo////_}"
        echo "::set-env name=repo::$repo"
      env:
        github_repo: ${{ github.repository }}
    - run: |
        curl \
        -XPOST \
        -H "Authorization: token ${{ secrets.PA_TOKEN }}" \
        -H "Accept: application/vnd.github.everest-preview+json" \
        -H "Content-Type: application/json" https://api.github.com/repos/tbrand-aa/pipeline-base/dispatches \
        --data '{"event_type": "integration-test_${{ env.repo }}", "client_payload": { "environment": "acceptance", "repository_name": "${{ github.repository }}", "repository_sha": "${{ github.sha }}"  }}'
